### ISSUE TITLE
Loss problem

### ISSUE THREAD

**Issue by LittleStar-yyy** [chichilicious/Generalized-Zero-Shot-Learning-via-Aligned-Variational-Autoencoders#1]
Hi, I've runed your code, I found a problem: when I trained the VAE model, the loss decreased before the epoch 22, but the loss increased very fast after the epoch 22. I think it's not normal, looking forward to your reply.

**Comment by sbharadwajj** [comment]
Hello,

I am so sorry I just saw this. Yes even in the official implementation the loss increases after epoch 22 because we are including a new loss term using the annealing scheme. So the entire loss term has 3 parts and one of the part is included only after 22nd epoch
