### ISSUE TITLE
why don't my download dataset have val_loc and train_loc ?

### ISSUE THREAD

**Issue by ghost** [chichilicious/Generalized-Zero-Shot-Learning-via-Aligned-Variational-Autoencoders#2]
I saw your dataset have the keys: val_loc, tain_loc, but why don't my download dataset have val_loc and train_loc? I just saw trainval_loc.

**Comment by liulu112601** [comment]
me2, any updates?

**Comment by sbharadwajj** [comment]
Hello,

Sorry I just saw these.  Did you download the proposed split?

**Comment by tiangarin** [comment]
I am also confused about it, can anyone give me some suggestion?

**Comment by sbharadwajj** [comment]
Can you check the dataset the author has provided in his official implementation [here](https://github.com/edgarschnfld/CADA-VAE-PyTorch)? There is a dropbox link and maybe that will help :)

**Comment by tiangarin** [comment]
> Can you check the dataset the author has provided in his official implementation [here](https://github.com/edgarschnfld/CADA-VAE-PyTorch)? There is a dropbox link and maybe that will help :)

I very appreciate your reply! It solves my problem.

**Comment by sbharadwajj** [comment]
Okay, good! I will close this issue then.
